version: "3"

services:
  home:
    image: lissy93/dashy
    container_name: Dashy
    ports: 
    - "4000:80"
    restart: always
    environment:
    - NODE_ENV=production
  notes:
    image: zadam/trilium:0.59-latest
    container_name: Trilium
    ports:
    - "4010:8080"
    restart: always
    volumes:
    - trilium-data:/home/node/trilium-data
  # container:
  #   image: portainer/portainer-ce
  #   container_name: Portainer
  #   ports:
  #   - "9443:9443"
  #   restart: always
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   - portainer_data:/data
  uptime:
    image: louislam/uptime-kuma:1
    container_name: Uptime-Kuma
    ports:
    - "3001:3001"
    restart: always
    volumes:
    - uptime-kuma:/app/data

volumes:
  uptime-kuma:
  trilium-data:
  portainer_data: